import type React from 'react';
import type { RenderableUnit } from '../types/editor.types';

export interface UnitRendererProps {
  unit: RenderableUnit;
  isMeasuring?: boolean;
  template: string;
  sections: any[];
  customStyles: any;
  headerStyles: any;
  editablePersonalInfo: any;
  setEditablePersonalInfo: React.Dispatch<React.SetStateAction<any>>;
  editableExperiences: any[];
  setEditableExperiences: React.Dispatch<React.SetStateAction<any[]>>;
  editableProjects: any[];
  setEditableProjects: React.Dispatch<React.SetStateAction<any[]>>;
  editableEducations: any[];
  setEditableEducations: React.Dispatch<React.SetStateAction<any[]>>;
  editableSkills: any[];
  setEditableSkills: React.Dispatch<React.SetStateAction<any[]>>;
  editableSummary: string;
  setEditableSummary: (val: string) => void;
  activeSectionSettings: string | null;
  setActiveSectionSettings: (val: string | null) => void;
  popoverPosition: { top: number; left: number } | null;
  setPopoverPosition: (pos: { top: number; left: number } | null) => void;
  setHeaderStyles: React.Dispatch<React.SetStateAction<any>>;
  setSections: React.Dispatch<React.SetStateAction<any[]>>;
  editingSectionTitleId: string | null;
  setEditingSectionTitleId: (id: string | null) => void;
  editingLanguagesId: string | null;
  setEditingLanguagesId: (id: string | null) => void;
  hoveredSectionId: string | null;
  setHoveredSectionId: (id: string | null) => void;
  handleMoveSection: (id: string, dir: 'up' | 'down') => void;
  handleQuickAddSectionItem: (id: string) => void;
  setOpenSectionAiModalId: (id: string | null) => void;
  handleMouseEnterSuggestion: (id: string) => void;
  handleMouseLeaveSuggestion: () => void;
  reviewedActions: Record<string, string>;
  renderHoverAiControls: (key: string, text: string, presets: any[]) => React.ReactNode;
  isRephrasing: Record<string, boolean>;
  handleMoveExperience: (idx: number, dir: 'up' | 'down') => void;
  handleAddExperienceBullet: (idx: number) => void;
  handleRemoveExperienceBullet: (expIdx: number, bulletIdx: number) => void;
  handleBulletKeyDown: (e: React.KeyboardEvent<HTMLTextAreaElement>, type: 'experience' | 'education' | 'custom' | 'project', itemId: string, itemIdx: number, bulletIdx: number, bullets: string[]) => void;
  handleMoveProject: (idx: number, dir: 'up' | 'down') => void;
  handleAddProjectBullet: (idx: number) => void;
  handleRemoveProjectBullet: (projIdx: number, bulletIdx: number) => void;
  handleMoveEducation: (idx: number, dir: 'up' | 'down') => void;
  handleAddEducationBullet: (idx: number) => void;
  handleRemoveEducationBullet: (eduIdx: number, bulletIdx: number) => void;
  languagesFirst: boolean;
  setLanguagesFirst: (val: boolean) => void;
  languagesTitle: string;
  setLanguagesTitle: (val: string) => void;
  targetLanguage: 'en' | 'de';
  categoryOrder: string[];
  handleMoveSkillCategory?: (catName: string, dir: 'up' | 'down') => void;
  getLocalizedCategoryName: (cat: string) => string;
  getAlertsFor: (section: string) => any[];
  toggleSectionVisibility?: (sectionId: string) => void;
  onResetToMasterProfile?: (sectionId: string) => void;
}
