# Generated by Django 4.2.30 on 2026-07-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='linkedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
