# Generated by Django 4.2.30 on 2026-07-14 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_profile', '0003_personalinfo_date_of_birth_personalinfo_github_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
