# Generated by Django 4.2.30 on 2026-08-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_profile', '0004_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='signature_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
