# Generated by Django 4.2.30 on 2026-07-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
