# Generated by Django 4.2.30 on 2026-07-11 15:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetterVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_company', models.CharField(max_length=255)),
                ('target_role', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('tone', models.CharField(default='professional', max_length=50)),
                ('length', models.CharField(default='medium', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('target_company', models.CharField(max_length=255)),
                ('target_role', models.CharField(max_length=255)),
                ('ats_score', models.IntegerField(default=0)),
                ('tailored_summary', models.TextField(blank=True, null=True)),
                ('tailored_details', models.JSONField(blank=True, default=dict)),
                ('explanations', models.JSONField(blank=True, default=list)),
                ('template', models.CharField(choices=[('modern_minimalist', 'Modern Minimalist'), ('executive_professional', 'Executive Professional'), ('creative_tech', 'Creative Tech')], default='modern_minimalist', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
