# Generated by Django 4.2.30 on 2026-07-13 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_job_description'),
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletterversion',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_letters', to='applications.application'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to='applications.application'),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='validation_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
