# Generated by Django 4.2.30 on 2026-07-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_coverletterversion_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeversion',
            name='template',
            field=models.CharField(choices=[('modern_minimalist', 'Modern Minimalist'), ('executive_professional', 'Executive Professional'), ('creative_tech', 'Creative Tech'), ('pixel_perfect_pdf', 'Pixel Perfect CV Template')], default='modern_minimalist', max_length=50),
        ),
    ]
