# Generated by Django 4.2.30 on 2026-07-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_resumeversion_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeversion',
            name='template',
            field=models.CharField(choices=[('modern_minimalist', 'Modern Minimalist'), ('executive_professional', 'Executive Professional'), ('creative_tech', 'Creative Tech'), ('pixel_perfect_pdf', 'Pixel Perfect CV Template'), ('german_style_cv', 'German-Style CV Template')], default='modern_minimalist', max_length=50),
        ),
    ]
